CREATE SCHEMA IF NOT EXISTS SPRINGIFY;
CREATE TABLE IF NOT EXISTS ADDRESS (ID SERIAL NOT NULL, NAME VARCHAR(2000) NOT NULL, REG_DATE TIMESTAMP NOT NULL DEFAULT NOW(), MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY(ID));
CREATE TABLE IF NOT EXISTS USERS (ID SERIAL NOT NULL, NAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(500), 
	ADDRESS_ID INTEGER NOT NULL, STATE VARCHAR(20) NOT NULL, REG_DATE TIMESTAMP NOT NULL DEFAULT NOW(), MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
	CONSTRAINT USERS_PK PRIMARY KEY (ID),
	CONSTRAINT USERS_FK1 FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ID));