CREATE SCHEMA IF NOT EXISTS SPRINGIFY;
CREATE TABLE IF NOT EXISTS ADDRESS (ID SERIAL NOT NULL, NAME VARCHAR(2000) NOT NULL, REG_DATE TIMESTAMP NOT NULL DEFAULT NOW(), MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
	PRIMARY KEY(ID));
CREATE TABLE IF NOT EXISTS USERS (ID SERIAL NOT NULL, NAME VARCHAR(255) NOT NULL, LASTNAME VARCHAR(500), 
	ADDRESS_ID INTEGER NOT NULL, STATE VARCHAR(20) NOT NULL, REG_DATE TIMESTAMP NOT NULL DEFAULT NOW(), MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
	CONSTRAINT USERS_PK PRIMARY KEY (ID),
	CONSTRAINT USERS_FK1 FOREIGN KEY (ADDRESS_ID) REFERENCES ADDRESS(ID));
CREATE TABLE IF NOT EXISTS PROFILES (ID SERIAL NOT NULL, NAME VARCHAR(255) NOT NULL, ALIAS VARCHAR(500) NOT NULL, 
	REG_DATE TIMESTAMP NOT NULL DEFAULT NOW(), MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
	CONSTRAINT PROFILES_PK PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS USER_PROFILES_MAP (ID_USER INTEGER NOT NULL, ID_PROFILE INTEGER NOT NULL,
	CONSTRAINT USER_PROFILES_MAP_PK PRIMARY KEY (ID_USER, ID_PROFILE),
	CONSTRAINT USER_PROFILES_MAP_FK1 FOREIGN KEY (ID_USER) REFERENCES USERS(ID),
	CONSTRAINT USER_PROFILES_MAP_FK2 FOREIGN KEY (ID_PROFILE) REFERENCES PROFILES(ID));
CREATE TABLE IF NOT EXISTS ROLES (ID SERIAL NOT NULL, NAME VARCHAR(255) NOT NULL, ALIAS VARCHAR(500) NOT NULL, 
	REG_DATE TIMESTAMP NOT NULL DEFAULT NOW(), MOD_DATE TIMESTAMP NOT NULL DEFAULT NOW(),
	CONSTRAINT ROLES_PK PRIMARY KEY (ID));
CREATE TABLE IF NOT EXISTS PROFILES_ROLES_MAP (ID_PROFILE INTEGER NOT NULL, ID_ROLE INTEGER NOT NULL,
	CONSTRAINT PROFILES_ROLES_MAP_PK PRIMARY KEY (ID_PROFILE, ID_ROLE),
	CONSTRAINT PROFILES_ROLES_MAP_FK1 FOREIGN KEY (ID_PROFILE) REFERENCES PROFILES(ID),
	CONSTRAINT PROFILES_ROLES_MAP_FK2 FOREIGN KEY (ID_ROLE) REFERENCES ROLES(ID));